export type RiskLevel = 'low' | 'high'

export type DemoFile = {
  path: string
  risk: RiskLevel
  linesAdded: number
  linesRemoved: number
  hasMatchingTest: boolean
  autoCollapse: boolean
  diff: string
}

export const prTitle = 'Rename auth token API and update call sites'

export const aiSummary =
  'This PR renames `getAuthToken()` to `getSessionToken()` across the auth module and updates 4 call sites to match. It also regenerates the lockfile and adds a formatting pass on 2 unrelated files. The core risk is concentrated in `auth/session.ts` and `api/client.ts` — everything else is mechanical.'

export const files: DemoFile[] = [
  {
    path: 'src/auth/session.ts',
    risk: 'high',
    linesAdded: 18,
    linesRemoved: 12,
    hasMatchingTest: true,
    autoCollapse: false,
    diff: `- export function getAuthToken(userId: string) {
+ export function getSessionToken(userId: string) {
    const record = store.get(userId)
-   if (!record) throw new Error('no token')
+   if (!record || record.expiresAt < Date.now()) throw new Error('no valid session')
    return record.token
  }`,
  },
  {
    path: 'src/api/client.ts',
    risk: 'high',
    linesAdded: 6,
    linesRemoved: 6,
    hasMatchingTest: false,
    autoCollapse: false,
    diff: `- import { getAuthToken } from '../auth/session'
+ import { getSessionToken } from '../auth/session'

  function request(path: string) {
-   const token = getAuthToken(currentUser.id)
+   const token = getSessionToken(currentUser.id)
    return fetch(path, { headers: { Authorization: \`Bearer \${token}\` } })
  }`,
  },
  {
    path: 'src/components/Header.tsx',
    risk: 'low',
    linesAdded: 2,
    linesRemoved: 2,
    hasMatchingTest: false,
    autoCollapse: true,
    diff: `- import { getAuthToken } from '../auth/session'
+ import { getSessionToken } from '../auth/session'`,
  },
  {
    path: 'src/components/Settings.tsx',
    risk: 'low',
    linesAdded: 2,
    linesRemoved: 2,
    hasMatchingTest: false,
    autoCollapse: true,
    diff: `- import { getAuthToken } from '../auth/session'
+ import { getSessionToken } from '../auth/session'`,
  },
  {
    path: 'src/auth/session.test.ts',
    risk: 'low',
    linesAdded: 14,
    linesRemoved: 8,
    hasMatchingTest: true,
    autoCollapse: false,
    diff: `- test('getAuthToken returns token', () => { ... })
+ test('getSessionToken returns token for valid session', () => { ... })
+ test('getSessionToken throws on expired session', () => { ... })`,
  },
  {
    path: 'src/styles/theme.css',
    risk: 'low',
    linesAdded: 3,
    linesRemoved: 1,
    hasMatchingTest: false,
    autoCollapse: true,
    diff: `  .button-primary {
-   color: #fff;
+   color: #ffffff;
+   letter-spacing: 0.02em;
  }`,
  },
  {
    path: 'src/generated/api-types.ts',
    risk: 'low',
    linesAdded: 412,
    linesRemoved: 398,
    hasMatchingTest: false,
    autoCollapse: true,
    diff: `// auto-generated by openapi-codegen — 810 lines changed`,
  },
  {
    path: 'package-lock.json',
    risk: 'low',
    linesAdded: 940,
    linesRemoved: 12,
    hasMatchingTest: false,
    autoCollapse: true,
    diff: `// dependency lockfile — 952 lines changed`,
  },
]
